begin;

-- Internal helpers live outside the Data API surface. Public RPCs below are the
-- only supported write path for policy evaluation, coverage and handovers.
create schema if not exists private;
revoke all on schema private from public;

create table public.leave_policy_versions (
  id uuid primary key default gen_random_uuid(),
  version_number integer generated by default as identity unique,
  name text not null check (char_length(btrim(name)) between 1 and 120),
  effective_from date not null,
  rules jsonb not null check (jsonb_typeof(rules) = 'object'),
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table public.leave_policy_evaluations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  policy_version_id uuid not null references public.leave_policy_versions(id),
  leave_type text not null check (leave_type in ('annual', 'sick', 'casual', 'parental')),
  start_date date not null,
  end_date date not null,
  business_days integer not null check (business_days >= 0),
  overall_status text not null check (overall_status in ('pass', 'warning', 'fail')),
  checks jsonb not null check (jsonb_typeof(checks) = 'array'),
  reason_present boolean not null,
  created_at timestamptz not null default now(),
  check (end_date >= start_date)
);

create table public.department_coverage_rules (
  id uuid primary key default gen_random_uuid(),
  department text not null check (char_length(btrim(department)) between 1 and 120),
  minimum_available integer not null default 1 check (minimum_available >= 0),
  minimum_coverage_percent numeric(5,2) not null default 60
    check (minimum_coverage_percent between 0 and 100),
  maximum_concurrent_leave integer not null default 2 check (maximum_concurrent_leave >= 1),
  medium_risk_score integer not null default 35 check (medium_risk_score between 1 and 99),
  high_risk_score integer not null default 70 check (high_risk_score between 2 and 100),
  effective_from date not null default current_date,
  effective_to date,
  is_active boolean not null default true,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (effective_to is null or effective_to >= effective_from),
  check (high_risk_score > medium_risk_score)
);

create table public.critical_role_rules (
  id uuid primary key default gen_random_uuid(),
  department text not null check (char_length(btrim(department)) between 1 and 120),
  role_title text not null check (char_length(btrim(role_title)) between 1 and 160),
  minimum_available integer not null default 1 check (minimum_available >= 1),
  effective_from date not null default current_date,
  effective_to date,
  is_active boolean not null default true,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (effective_to is null or effective_to >= effective_from)
);

create table public.leave_coverage_snapshots (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  policy_evaluation_id uuid not null references public.leave_policy_evaluations(id),
  department text not null,
  employee_title text not null,
  leave_type text not null check (leave_type in ('annual', 'sick', 'casual', 'parental')),
  start_date date not null,
  end_date date not null,
  business_days integer not null check (business_days > 0),
  risk_score integer not null check (risk_score between 0 and 100),
  risk_level text not null check (risk_level in ('low', 'medium', 'high')),
  component_scores jsonb not null check (jsonb_typeof(component_scores) = 'object'),
  handover_required boolean not null default false,
  handover_reasons jsonb not null default '[]'::jsonb check (jsonb_typeof(handover_reasons) = 'array'),
  expires_at timestamptz not null default (now() + interval '1 hour'),
  used_at timestamptz,
  created_at timestamptz not null default now(),
  check (end_date >= start_date)
);

create table public.leave_coverage_snapshot_days (
  snapshot_id uuid not null references public.leave_coverage_snapshots(id) on delete cascade,
  day date not null,
  department_headcount integer not null check (department_headcount >= 0),
  approved_absent integer not null check (approved_absent >= 0),
  pending_requests integer not null check (pending_requests >= 0),
  projected_available integer not null check (projected_available >= 0),
  coverage_percent numeric(5,2) not null check (coverage_percent between 0 and 100),
  projected_concurrent_leave integer not null check (projected_concurrent_leave >= 0),
  critical_role_rules_at_risk integer not null check (critical_role_rules_at_risk >= 0),
  primary key (snapshot_id, day)
);

create table public.leave_coverage_alternatives (
  snapshot_id uuid not null references public.leave_coverage_snapshots(id) on delete cascade,
  rank smallint not null check (rank between 1 and 3),
  start_date date not null,
  end_date date not null,
  risk_score integer not null check (risk_score between 0 and 100),
  risk_level text not null check (risk_level in ('low', 'medium', 'high')),
  primary key (snapshot_id, rank),
  check (end_date >= start_date)
);

alter table public.leave_requests
  add column policy_evaluation_id uuid references public.leave_policy_evaluations(id),
  add column coverage_snapshot_id uuid references public.leave_coverage_snapshots(id),
  add column coverage_risk_level text check (coverage_risk_level in ('low', 'medium', 'high')),
  add column handover_required boolean not null default false,
  add column handover_requirement_reasons jsonb not null default '[]'::jsonb
    check (jsonb_typeof(handover_requirement_reasons) = 'array'),
  add column approval_override_reason text;

create table public.leave_handover_plans (
  id uuid primary key default gen_random_uuid(),
  leave_request_id uuid not null unique references public.leave_requests(id) on delete cascade,
  employee_id uuid not null references public.profiles(id) on delete cascade,
  backup_user_id uuid not null references public.profiles(id),
  summary text not null check (char_length(btrim(summary)) between 10 and 2000),
  status text not null default 'pending' check (status in ('pending', 'accepted', 'declined')),
  response_comment text,
  submitted_at timestamptz not null default now(),
  responded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (employee_id <> backup_user_id)
);

create table public.leave_handover_items (
  id uuid primary key default gen_random_uuid(),
  plan_id uuid not null references public.leave_handover_plans(id) on delete cascade,
  position integer not null check (position between 1 and 50),
  title text not null check (char_length(btrim(title)) between 1 and 160),
  details text not null default '' check (char_length(details) <= 2000),
  due_date date,
  resource_url text check (
    resource_url is null or
    (char_length(resource_url) <= 1000 and resource_url ~* '^https?://')
  ),
  created_at timestamptz not null default now(),
  unique (plan_id, position)
);

create table public.leave_handover_events (
  id bigint generated always as identity primary key,
  plan_id uuid not null references public.leave_handover_plans(id) on delete cascade,
  actor_id uuid not null references public.profiles(id),
  event_type text not null check (event_type in ('plan_saved', 'accepted', 'declined')),
  comment text not null default '' check (char_length(comment) <= 2000),
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now()
);

create index leave_policy_versions_effective_idx
  on public.leave_policy_versions (effective_from desc, version_number desc);
create index leave_policy_evaluations_user_created_idx
  on public.leave_policy_evaluations (user_id, created_at desc);
create index department_coverage_rules_lookup_idx
  on public.department_coverage_rules (lower(btrim(department)), effective_from desc)
  where is_active;
create unique index department_coverage_rules_active_version_idx
  on public.department_coverage_rules (lower(btrim(department)), effective_from)
  where is_active;
create index critical_role_rules_lookup_idx
  on public.critical_role_rules (lower(btrim(department)), lower(btrim(role_title)), effective_from desc)
  where is_active;
create unique index critical_role_rules_active_version_idx
  on public.critical_role_rules (lower(btrim(department)), lower(btrim(role_title)), effective_from)
  where is_active;
create index leave_coverage_snapshots_user_created_idx
  on public.leave_coverage_snapshots (user_id, created_at desc);
create index leave_coverage_snapshots_department_dates_idx
  on public.leave_coverage_snapshots (department, start_date, end_date);
create index leave_coverage_snapshot_days_day_idx
  on public.leave_coverage_snapshot_days (day, snapshot_id);
create unique index leave_requests_policy_evaluation_unique_idx
  on public.leave_requests (policy_evaluation_id) where policy_evaluation_id is not null;
create unique index leave_requests_coverage_snapshot_unique_idx
  on public.leave_requests (coverage_snapshot_id) where coverage_snapshot_id is not null;
create index leave_requests_department_active_dates_idx
  on public.leave_requests (department, start_date, end_date)
  where status in ('pending', 'approved', 'cancellation_pending');
create index leave_handover_plans_employee_status_idx
  on public.leave_handover_plans (employee_id, status, updated_at desc);
create index leave_handover_plans_backup_status_idx
  on public.leave_handover_plans (backup_user_id, status, updated_at desc);
create index leave_handover_items_plan_position_idx
  on public.leave_handover_items (plan_id, position);
create index leave_handover_events_plan_created_idx
  on public.leave_handover_events (plan_id, created_at);

insert into public.leave_policy_versions (name, effective_from, rules)
values (
  'LeaveWise default policy',
  '2000-01-01',
  jsonb_build_object(
    'minimumNoticeBusinessDays', jsonb_build_object(
      'annual', 3, 'sick', 0, 'casual', 1, 'parental', 14
    ),
    'maximumConsecutiveBusinessDays', jsonb_build_object(
      'annual', 20, 'sick', 10, 'casual', 5, 'parental', 30
    ),
    'allowPastDates', false,
    'requireReason', true
  )
);

insert into public.department_coverage_rules (
  department,
  minimum_available,
  minimum_coverage_percent,
  maximum_concurrent_leave,
  medium_risk_score,
  high_risk_score,
  effective_from
)
select distinct
  p.department,
  1,
  60,
  2,
  35,
  70,
  '2000-01-01'::date
from public.profiles p
where char_length(btrim(p.department)) > 0
on conflict do nothing;

-- Central, holiday-aware business-day functions. Active government and company
-- calendar events both remove a weekday from the working-day count.
create or replace function private.is_business_day(p_day date)
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  select
    extract(isodow from p_day) < 6
    and not exists (
      select 1
      from public.company_calendar_events e
      where e.event_date = p_day
        and e.is_active
    );
$$;

create or replace function private.business_days_between(p_start_date date, p_end_date date)
returns integer
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  select case
    when p_start_date is null or p_end_date is null or p_end_date < p_start_date then 0
    else (
      select count(*)::integer
      from generate_series(
        p_start_date::timestamp,
        p_end_date::timestamp,
        interval '1 day'
      ) as days(day_value)
      where private.is_business_day(days.day_value::date)
    )
  end;
$$;

create or replace function private.business_date_after(p_start_date date, p_offset integer)
returns date
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  select candidate.day_value::date
  from generate_series(
    p_start_date::timestamp,
    (p_start_date + 730)::timestamp,
    interval '1 day'
  ) with ordinality as candidate(day_value, position)
  where private.is_business_day(candidate.day_value::date)
  order by candidate.day_value
  offset greatest(coalesce(p_offset, 0), 0)
  limit 1;
$$;

create or replace function private.apply_authoritative_business_days()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
  if new.end_date < new.start_date then
    raise exception 'End date must be on or after start date';
  end if;

  new.total_days := private.business_days_between(new.start_date, new.end_date);
  if new.total_days < 1 then
    raise exception 'Leave dates must include at least one working day';
  end if;

  return new;
end;
$$;

drop trigger if exists apply_authoritative_business_days on public.leave_requests;
create trigger apply_authoritative_business_days
before insert or update of start_date, end_date on public.leave_requests
for each row execute function private.apply_authoritative_business_days();

create or replace function private.require_approved_profile()
returns public.profiles
language plpgsql
stable
security definer
set search_path = pg_catalog, public
as $$
declare
  v_profile public.profiles;
begin
  if auth.uid() is null then
    raise exception 'Authentication is required' using errcode = '28000';
  end if;

  select p.*
  into v_profile
  from public.profiles p
  where p.id = auth.uid()
    and p.approval_status = 'approved';

  if not found then
    raise exception 'An approved LeaveWise account is required' using errcode = '42501';
  end if;

  return v_profile;
end;
$$;

create or replace function private.create_policy_evaluation(
  p_user_id uuid,
  p_leave_type text,
  p_start_date date,
  p_end_date date,
  p_reason text
)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_policy public.leave_policy_versions;
  v_business_days integer;
  v_notice_days integer;
  v_required_notice integer;
  v_maximum_days integer;
  v_remaining integer;
  v_overlap boolean;
  v_checks jsonb := '[]'::jsonb;
  v_status text := 'pass';
  v_check_status text;
  v_evaluation_id uuid;
begin
  select policy.*
  into v_policy
  from public.leave_policy_versions policy
  where policy.effective_from <= p_start_date
  order by policy.effective_from desc, policy.version_number desc
  limit 1;

  if not found then
    raise exception 'No leave policy is effective for the selected dates';
  end if;

  v_business_days := private.business_days_between(p_start_date, p_end_date);
  v_notice_days := case
    when p_start_date <= current_date then 0
    else private.business_days_between(current_date + 1, p_start_date - 1)
  end;
  v_required_notice := coalesce(
    (v_policy.rules -> 'minimumNoticeBusinessDays' ->> p_leave_type)::integer,
    0
  );
  v_maximum_days := coalesce(
    (v_policy.rules -> 'maximumConsecutiveBusinessDays' ->> p_leave_type)::integer,
    366
  );

  select case p_leave_type
    when 'annual' then b.annual_total - b.annual_used
    when 'sick' then b.sick_total - b.sick_used
    when 'casual' then b.casual_total - b.casual_used
    when 'parental' then b.parental_total - b.parental_used
  end
  into v_remaining
  from public.leave_balances b
  where b.user_id = p_user_id;

  v_remaining := greatest(coalesce(v_remaining, 0), 0);

  select exists (
    select 1
    from public.leave_requests request
    where request.user_id = p_user_id
      and request.status in ('pending', 'approved', 'cancellation_pending')
      and daterange(request.start_date, request.end_date, '[]')
          && daterange(p_start_date, p_end_date, '[]')
  ) into v_overlap;

  v_check_status := case
    when coalesce((v_policy.rules ->> 'allowPastDates')::boolean, false)
      or p_start_date >= current_date then 'pass'
    else 'fail'
  end;
  if v_check_status = 'fail' then v_status := 'fail'; end if;
  v_checks := v_checks || jsonb_build_array(jsonb_build_object(
    'code', 'date_not_in_past',
    'label', 'Requested dates',
    'status', v_check_status,
    'message', case when v_check_status = 'pass'
      then 'The request starts on an allowed date.'
      else 'Leave cannot start in the past.' end
  ));

  v_check_status := case when v_business_days > 0 then 'pass' else 'fail' end;
  if v_check_status = 'fail' then v_status := 'fail'; end if;
  v_checks := v_checks || jsonb_build_array(jsonb_build_object(
    'code', 'business_days',
    'label', 'Working days',
    'status', v_check_status,
    'message', format('%s business day(s), excluding weekends and published holidays.', v_business_days),
    'actual', v_business_days
  ));

  v_check_status := case
    when not coalesce((v_policy.rules ->> 'requireReason')::boolean, true)
      or char_length(btrim(coalesce(p_reason, ''))) > 0 then 'pass'
    else 'fail'
  end;
  if v_check_status = 'fail' then v_status := 'fail'; end if;
  v_checks := v_checks || jsonb_build_array(jsonb_build_object(
    'code', 'reason_required',
    'label', 'Reason supplied',
    'status', v_check_status,
    'message', case when v_check_status = 'pass'
      then 'A reason has been supplied.'
      else 'A reason is required.' end
  ));

  if char_length(btrim(coalesce(p_reason, ''))) between 1 and 9 and v_status <> 'fail' then
    v_status := 'warning';
  end if;
  v_checks := v_checks || jsonb_build_array(jsonb_build_object(
    'code', 'reason_detail',
    'label', 'Reason detail',
    'status', case
      when char_length(btrim(coalesce(p_reason, ''))) = 0 then 'fail'
      when char_length(btrim(p_reason)) < 10 then 'warning'
      else 'pass' end,
    'message', case
      when char_length(btrim(coalesce(p_reason, ''))) = 0 then 'No reason was supplied.'
      when char_length(btrim(p_reason)) < 10 then 'Add a little more detail for a faster review.'
      else 'The reason contains enough detail for review.' end
  ));

  v_check_status := case when v_notice_days >= v_required_notice then 'pass' else 'fail' end;
  if v_check_status = 'fail' then v_status := 'fail'; end if;
  v_checks := v_checks || jsonb_build_array(jsonb_build_object(
    'code', 'minimum_notice',
    'label', 'Notice period',
    'status', v_check_status,
    'message', format('%s of %s required business-day notice provided.', v_notice_days, v_required_notice),
    'actual', v_notice_days,
    'required', v_required_notice
  ));

  v_check_status := case when v_business_days <= v_maximum_days then 'pass' else 'fail' end;
  if v_check_status = 'fail' then v_status := 'fail'; end if;
  v_checks := v_checks || jsonb_build_array(jsonb_build_object(
    'code', 'maximum_duration',
    'label', 'Maximum duration',
    'status', v_check_status,
    'message', format('%s of %s permitted consecutive business days requested.', v_business_days, v_maximum_days),
    'actual', v_business_days,
    'maximum', v_maximum_days
  ));

  v_check_status := case when v_business_days <= v_remaining then 'pass' else 'fail' end;
  if v_check_status = 'fail' then v_status := 'fail'; end if;
  v_checks := v_checks || jsonb_build_array(jsonb_build_object(
    'code', 'leave_balance',
    'label', 'Available balance',
    'status', v_check_status,
    'message', format('%s day(s) requested with %s day(s) available.', v_business_days, v_remaining),
    'requested', v_business_days,
    'available', v_remaining
  ));

  v_check_status := case when not v_overlap then 'pass' else 'fail' end;
  if v_check_status = 'fail' then v_status := 'fail'; end if;
  v_checks := v_checks || jsonb_build_array(jsonb_build_object(
    'code', 'date_overlap',
    'label', 'Existing requests',
    'status', v_check_status,
    'message', case when v_overlap
      then 'The selected dates overlap an active leave request.'
      else 'No active leave request overlaps these dates.' end
  ));

  insert into public.leave_policy_evaluations (
    user_id,
    policy_version_id,
    leave_type,
    start_date,
    end_date,
    business_days,
    overall_status,
    checks,
    reason_present
  ) values (
    p_user_id,
    v_policy.id,
    p_leave_type,
    p_start_date,
    p_end_date,
    v_business_days,
    v_status,
    v_checks,
    char_length(btrim(coalesce(p_reason, ''))) > 0
  ) returning id into v_evaluation_id;

  return v_evaluation_id;
end;
$$;

create or replace function private.calculate_coverage(
  p_user_id uuid,
  p_department text,
  p_employee_title text,
  p_start_date date,
  p_end_date date
)
returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, public
as $$
declare
  v_rule public.department_coverage_rules%rowtype;
  v_day date;
  v_headcount integer;
  v_approved_absent integer;
  v_pending_requests integer;
  v_projected_available integer;
  v_projected_concurrent integer;
  v_requester_already_absent boolean;
  v_coverage_percent numeric(5,2);
  v_critical_at_risk integer;
  v_daily_facts jsonb := '[]'::jsonb;
  v_min_coverage numeric(5,2) := 100;
  v_min_projected_available integer;
  v_max_concurrent integer := 0;
  v_max_critical_at_risk integer := 0;
  v_coverage_component integer;
  v_concurrency_component integer;
  v_critical_component integer;
  v_risk_score integer;
  v_risk_level text;
begin
  select rule.*
  into v_rule
  from public.department_coverage_rules rule
  where lower(btrim(rule.department)) = lower(btrim(p_department))
    and rule.is_active
    and rule.effective_from <= p_start_date
    and (rule.effective_to is null or rule.effective_to >= p_end_date)
  order by rule.effective_from desc, rule.created_at desc
  limit 1;

  if not found then
    v_rule.minimum_available := 1;
    v_rule.minimum_coverage_percent := 60;
    v_rule.maximum_concurrent_leave := 2;
    v_rule.medium_risk_score := 35;
    v_rule.high_risk_score := 70;
  end if;

  select count(*)::integer
  into v_headcount
  from public.profiles profile
  where profile.approval_status = 'approved'
    and lower(btrim(profile.department)) = lower(btrim(p_department));

  v_min_projected_available := v_headcount;

  for v_day in
    select days.day_value::date
    from generate_series(
      p_start_date::timestamp,
      p_end_date::timestamp,
      interval '1 day'
    ) as days(day_value)
    where private.is_business_day(days.day_value::date)
    order by days.day_value
  loop
    select count(distinct request.user_id)::integer
    into v_approved_absent
    from public.leave_requests request
    where lower(btrim(request.department)) = lower(btrim(p_department))
      and request.status in ('approved', 'cancellation_pending')
      and v_day between request.start_date and request.end_date;

    select exists (
      select 1
      from public.leave_requests request
      where request.user_id = p_user_id
        and request.status in ('approved', 'cancellation_pending')
        and v_day between request.start_date and request.end_date
    ) into v_requester_already_absent;

    select count(distinct request.user_id)::integer
    into v_pending_requests
    from public.leave_requests request
    where lower(btrim(request.department)) = lower(btrim(p_department))
      and request.status = 'pending'
      and request.user_id <> p_user_id
      and v_day between request.start_date and request.end_date;

    v_projected_available := greatest(
      0,
      v_headcount - v_approved_absent - case when v_requester_already_absent then 0 else 1 end
    );
    v_projected_concurrent :=
      v_approved_absent + v_pending_requests + case when v_requester_already_absent then 0 else 1 end;
    v_coverage_percent := case
      when v_headcount = 0 then 0
      else round((v_projected_available::numeric * 100) / v_headcount, 2)
    end;

    select count(*)::integer
    into v_critical_at_risk
    from public.critical_role_rules critical
    where lower(btrim(critical.department)) = lower(btrim(p_department))
      and critical.is_active
      and critical.effective_from <= v_day
      and (critical.effective_to is null or critical.effective_to >= v_day)
      and (
        select count(*)::integer
        from public.profiles candidate
        where candidate.approval_status = 'approved'
          and lower(btrim(candidate.department)) = lower(btrim(p_department))
          and lower(btrim(candidate.title)) = lower(btrim(critical.role_title))
          and candidate.id <> p_user_id
          and not exists (
            select 1
            from public.leave_requests existing_leave
            where existing_leave.user_id = candidate.id
              and existing_leave.status in ('approved', 'cancellation_pending')
              and v_day between existing_leave.start_date and existing_leave.end_date
          )
      ) < critical.minimum_available;

    v_min_coverage := least(v_min_coverage, v_coverage_percent);
    v_min_projected_available := least(v_min_projected_available, v_projected_available);
    v_max_concurrent := greatest(v_max_concurrent, v_projected_concurrent);
    v_max_critical_at_risk := greatest(v_max_critical_at_risk, v_critical_at_risk);

    v_daily_facts := v_daily_facts || jsonb_build_array(jsonb_build_object(
      'date', v_day,
      'departmentHeadcount', v_headcount,
      'approvedAbsent', v_approved_absent,
      'pendingRequests', v_pending_requests,
      'projectedAvailable', v_projected_available,
      'coveragePercent', v_coverage_percent,
      'projectedConcurrentLeave', v_projected_concurrent,
      'criticalRoleRulesAtRisk', v_critical_at_risk
    ));
  end loop;

  v_coverage_component := case
    when v_min_projected_available < v_rule.minimum_available
      or v_min_coverage < v_rule.minimum_coverage_percent
      then least(
        100,
        70
        + greatest(v_rule.minimum_available - v_min_projected_available, 0) * 10
        + greatest(round(v_rule.minimum_coverage_percent - v_min_coverage)::integer, 0)
      )
    else least(60, greatest(0, round((100 - v_min_coverage) * 0.35)::integer))
  end;

  v_concurrency_component := case
    when v_max_concurrent > v_rule.maximum_concurrent_leave
      then least(100, 70 + ((v_max_concurrent - v_rule.maximum_concurrent_leave) * 10))
    else least(
      60,
      round((v_max_concurrent::numeric / greatest(v_rule.maximum_concurrent_leave, 1)) * 40)::integer
    )
  end;

  v_critical_component := case when v_max_critical_at_risk > 0 then 100 else 0 end;
  v_risk_score := least(
    100,
    round(
      (v_coverage_component * 0.45)
      + (v_concurrency_component * 0.20)
      + (v_critical_component * 0.35)
    )::integer
  );

  if v_max_critical_at_risk > 0
     or v_min_projected_available < v_rule.minimum_available then
    v_risk_score := greatest(v_risk_score, v_rule.high_risk_score);
  end if;

  v_risk_level := case
    when v_risk_score >= v_rule.high_risk_score then 'high'
    when v_risk_score >= v_rule.medium_risk_score then 'medium'
    else 'low'
  end;

  return jsonb_build_object(
    'riskScore', v_risk_score,
    'riskLevel', v_risk_level,
    'componentScores', jsonb_build_object(
      'coverage', v_coverage_component,
      'concurrency', v_concurrency_component,
      'criticalRole', v_critical_component,
      'overall', v_risk_score
    ),
    'dailyFacts', v_daily_facts,
    'criticalRoleTriggered', v_max_critical_at_risk > 0,
    'rule', jsonb_build_object(
      'minimumAvailable', v_rule.minimum_available,
      'minimumCoveragePercent', v_rule.minimum_coverage_percent,
      'maximumConcurrentLeave', v_rule.maximum_concurrent_leave,
      'mediumRiskScore', v_rule.medium_risk_score,
      'highRiskScore', v_rule.high_risk_score
    )
  );
end;
$$;

create or replace function public.preview_leave_request(
  p_leave_type text,
  p_start_date date,
  p_end_date date,
  p_reason text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_profile public.profiles;
  v_evaluation public.leave_policy_evaluations;
  v_evaluation_id uuid;
  v_policy_version integer;
  v_coverage jsonb;
  v_candidates jsonb := '[]'::jsonb;
  v_alternatives jsonb := '[]'::jsonb;
  v_candidate_start date;
  v_candidate_end date;
  v_candidate_coverage jsonb;
  v_snapshot_id uuid;
  v_handover_required boolean;
  v_handover_reasons jsonb := '[]'::jsonb;
  v_is_critical_role boolean;
begin
  v_profile := private.require_approved_profile();

  if p_leave_type not in ('annual', 'sick', 'casual', 'parental') then
    raise exception 'Invalid leave type';
  end if;
  if p_start_date is null or p_end_date is null or p_end_date < p_start_date then
    raise exception 'End date must be on or after start date';
  end if;
  if p_end_date - p_start_date > 366 then
    raise exception 'A leave preview cannot span more than 366 calendar days';
  end if;

  v_evaluation_id := private.create_policy_evaluation(
    v_profile.id,
    p_leave_type,
    p_start_date,
    p_end_date,
    p_reason
  );

  select evaluation.*
  into v_evaluation
  from public.leave_policy_evaluations evaluation
  where evaluation.id = v_evaluation_id;

  select policy.version_number
  into v_policy_version
  from public.leave_policy_versions policy
  where policy.id = v_evaluation.policy_version_id;

  if v_evaluation.business_days < 1 then
    raise exception 'Leave dates must include at least one working day';
  end if;

  v_coverage := private.calculate_coverage(
    v_profile.id,
    v_profile.department,
    v_profile.title,
    p_start_date,
    p_end_date
  );

  for v_candidate_start in
    select days.day_value::date
    from generate_series(
      (p_end_date + 1)::timestamp,
      (p_end_date + 90)::timestamp,
      interval '1 day'
    ) as days(day_value)
    where private.is_business_day(days.day_value::date)
    order by days.day_value
  loop
    v_candidate_end := private.business_date_after(
      v_candidate_start,
      v_evaluation.business_days - 1
    );
    v_candidate_coverage := private.calculate_coverage(
      v_profile.id,
      v_profile.department,
      v_profile.title,
      v_candidate_start,
      v_candidate_end
    );
    v_candidates := v_candidates || jsonb_build_array(jsonb_build_object(
      'startDate', v_candidate_start,
      'endDate', v_candidate_end,
      'riskScore', (v_candidate_coverage ->> 'riskScore')::integer,
      'riskLevel', v_candidate_coverage ->> 'riskLevel'
    ));
  end loop;

  select coalesce(jsonb_agg(candidate.item order by candidate.risk_score, candidate.start_date), '[]'::jsonb)
  into v_alternatives
  from (
    select
      value as item,
      (value ->> 'riskScore')::integer as risk_score,
      (value ->> 'startDate')::date as start_date
    from jsonb_array_elements(v_candidates)
    order by (value ->> 'riskScore')::integer, (value ->> 'startDate')::date
    limit 3
  ) candidate;

  if jsonb_array_length(v_alternatives) <> 3 then
    raise exception 'Unable to calculate three alternative date ranges';
  end if;

  select exists (
    select 1
    from public.critical_role_rules critical
    where lower(btrim(critical.department)) = lower(btrim(v_profile.department))
      and lower(btrim(critical.role_title)) = lower(btrim(v_profile.title))
      and critical.is_active
      and critical.effective_from <= p_start_date
      and (critical.effective_to is null or critical.effective_to >= p_end_date)
  ) into v_is_critical_role;

  if v_evaluation.business_days >= 3 then
    v_handover_reasons := v_handover_reasons || '"three_or_more_business_days"'::jsonb;
  end if;
  if v_is_critical_role then
    v_handover_reasons := v_handover_reasons || '"critical_role"'::jsonb;
  end if;
  if v_coverage ->> 'riskLevel' = 'high' then
    v_handover_reasons := v_handover_reasons || '"high_coverage_risk"'::jsonb;
  end if;
  v_handover_required := jsonb_array_length(v_handover_reasons) > 0;

  insert into public.leave_coverage_snapshots (
    user_id,
    policy_evaluation_id,
    department,
    employee_title,
    leave_type,
    start_date,
    end_date,
    business_days,
    risk_score,
    risk_level,
    component_scores,
    handover_required,
    handover_reasons
  ) values (
    v_profile.id,
    v_evaluation.id,
    v_profile.department,
    v_profile.title,
    p_leave_type,
    p_start_date,
    p_end_date,
    v_evaluation.business_days,
    (v_coverage ->> 'riskScore')::integer,
    v_coverage ->> 'riskLevel',
    v_coverage -> 'componentScores',
    v_handover_required,
    v_handover_reasons
  ) returning id into v_snapshot_id;

  insert into public.leave_coverage_snapshot_days (
    snapshot_id,
    day,
    department_headcount,
    approved_absent,
    pending_requests,
    projected_available,
    coverage_percent,
    projected_concurrent_leave,
    critical_role_rules_at_risk
  )
  select
    v_snapshot_id,
    (fact.value ->> 'date')::date,
    (fact.value ->> 'departmentHeadcount')::integer,
    (fact.value ->> 'approvedAbsent')::integer,
    (fact.value ->> 'pendingRequests')::integer,
    (fact.value ->> 'projectedAvailable')::integer,
    (fact.value ->> 'coveragePercent')::numeric,
    (fact.value ->> 'projectedConcurrentLeave')::integer,
    (fact.value ->> 'criticalRoleRulesAtRisk')::integer
  from jsonb_array_elements(v_coverage -> 'dailyFacts') as fact(value);

  insert into public.leave_coverage_alternatives (
    snapshot_id,
    rank,
    start_date,
    end_date,
    risk_score,
    risk_level
  )
  select
    v_snapshot_id,
    alternative.position::smallint,
    (alternative.value ->> 'startDate')::date,
    (alternative.value ->> 'endDate')::date,
    (alternative.value ->> 'riskScore')::integer,
    alternative.value ->> 'riskLevel'
  from jsonb_array_elements(v_alternatives) with ordinality
    as alternative(value, position);

  return jsonb_build_object(
    'policyEvaluationId', v_evaluation.id,
    'policy', jsonb_build_object(
      'status', v_evaluation.overall_status,
      'businessDays', v_evaluation.business_days,
      'checks', v_evaluation.checks,
      'version', v_policy_version,
      'versionId', v_evaluation.policy_version_id
    ),
    'coverageSnapshotId', v_snapshot_id,
    'coverageImpact', v_coverage || jsonb_build_object(
      'recommendedDates', v_alternatives
    ),
    'handoverRequired', v_handover_required,
    'handoverReasons', v_handover_reasons,
    'expiresAt', now() + interval '1 hour'
  );
end;
$$;

create or replace function public.get_handover_candidates()
returns table (
  id uuid,
  name text,
  title text,
  department text
)
language plpgsql
stable
security definer
set search_path = pg_catalog, public
as $$
declare
  v_profile public.profiles;
begin
  v_profile := private.require_approved_profile();

  return query
  select coworker.id, coworker.name, coworker.title, coworker.department
  from public.profiles coworker
  where coworker.approval_status = 'approved'
    and coworker.role = 'employee'
    and coworker.id <> v_profile.id
    and lower(btrim(coworker.department)) = lower(btrim(v_profile.department))
  order by coworker.name, coworker.id;
end;
$$;

create or replace function public.get_assigned_handovers()
returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, public
as $$
declare
  v_profile public.profiles;
  v_result jsonb;
begin
  v_profile := private.require_approved_profile();

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'planId', plan.id,
        'leaveRequestId', plan.leave_request_id,
        'ownerName', owner_profile.name,
        'startDate', request.start_date,
        'endDate', request.end_date,
        'summary', plan.summary,
        'items', coalesce((
          select jsonb_agg(
            jsonb_build_object(
              'id', item.id,
              'title', item.title,
              'details', item.details,
              'dueDate', item.due_date,
              'resourceUrl', item.resource_url
            ) order by item.position
          )
          from public.leave_handover_items item
          where item.plan_id = plan.id
        ), '[]'::jsonb),
        'status', plan.status,
        'responseComment', plan.response_comment,
        'submittedAt', plan.submitted_at,
        'respondedAt', plan.responded_at
      ) order by request.start_date, plan.created_at
    ),
    '[]'::jsonb
  )
  into v_result
  from public.leave_handover_plans plan
  join public.leave_requests request on request.id = plan.leave_request_id
  join public.profiles owner_profile on owner_profile.id = plan.employee_id
  where plan.backup_user_id = v_profile.id;

  return v_result;
end;
$$;

create or replace function public.save_handover_plan(
  p_request_id uuid,
  p_payload jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_profile public.profiles;
  v_request public.leave_requests;
  v_backup public.profiles;
  v_plan public.leave_handover_plans;
  v_backup_user_id uuid;
  v_summary text;
  v_items jsonb;
begin
  v_profile := private.require_approved_profile();

  if p_payload is null or jsonb_typeof(p_payload) <> 'object' then
    raise exception 'Handover details must be supplied as an object';
  end if;

  select request.*
  into v_request
  from public.leave_requests request
  where request.id = p_request_id
    and request.user_id = v_profile.id
  for update;

  if not found then
    raise exception 'Leave request not found' using errcode = 'P0002';
  end if;
  if v_request.status <> 'pending' then
    raise exception 'A handover can only be edited while the leave request is pending';
  end if;

  begin
    v_backup_user_id := nullif(p_payload ->> 'backupUserId', '')::uuid;
  exception when invalid_text_representation then
    raise exception 'Select a valid backup employee';
  end;
  v_summary := btrim(coalesce(p_payload ->> 'summary', ''));
  v_items := coalesce(p_payload -> 'items', '[]'::jsonb);

  if v_backup_user_id is null then
    raise exception 'A backup employee is required';
  end if;
  if char_length(v_summary) < 10 or char_length(v_summary) > 2000 then
    raise exception 'Handover summary must contain between 10 and 2000 characters';
  end if;
  if jsonb_typeof(v_items) <> 'array'
     or jsonb_array_length(v_items) < 1
     or jsonb_array_length(v_items) > 50 then
    raise exception 'Add between 1 and 50 handover items';
  end if;
  if exists (
    select 1
    from jsonb_array_elements(v_items) item(value)
    where char_length(btrim(coalesce(item.value ->> 'title', ''))) not between 1 and 160
       or char_length(coalesce(item.value ->> 'details', '')) > 2000
       or char_length(coalesce(item.value ->> 'resourceUrl', '')) > 1000
       or (
         nullif(item.value ->> 'resourceUrl', '') is not null
         and (item.value ->> 'resourceUrl') !~* '^https?://'
       )
  ) then
    raise exception 'One or more handover items contain invalid details';
  end if;

  select backup.*
  into v_backup
  from public.profiles backup
  where backup.id = v_backup_user_id
    and backup.id <> v_profile.id
    and backup.approval_status = 'approved'
    and backup.role = 'employee'
    and lower(btrim(backup.department)) = lower(btrim(v_profile.department));

  if not found then
    raise exception 'The selected backup must be an approved employee in your department';
  end if;

  insert into public.leave_handover_plans (
    leave_request_id,
    employee_id,
    backup_user_id,
    summary,
    status,
    response_comment,
    submitted_at,
    responded_at
  ) values (
    v_request.id,
    v_profile.id,
    v_backup.id,
    v_summary,
    'pending',
    null,
    now(),
    null
  )
  on conflict (leave_request_id) do update
  set backup_user_id = excluded.backup_user_id,
      summary = excluded.summary,
      status = 'pending',
      response_comment = null,
      submitted_at = now(),
      responded_at = null,
      updated_at = now()
  returning * into v_plan;

  delete from public.leave_handover_items item
  where item.plan_id = v_plan.id;

  insert into public.leave_handover_items (
    plan_id,
    position,
    title,
    details,
    due_date,
    resource_url
  )
  select
    v_plan.id,
    item.position::integer,
    btrim(item.value ->> 'title'),
    coalesce(item.value ->> 'details', ''),
    nullif(item.value ->> 'dueDate', '')::date,
    nullif(item.value ->> 'resourceUrl', '')
  from jsonb_array_elements(v_items) with ordinality as item(value, position);

  insert into public.leave_handover_events (
    plan_id,
    actor_id,
    event_type,
    metadata
  ) values (
    v_plan.id,
    v_profile.id,
    'plan_saved',
    jsonb_build_object(
      'backupUserId', v_backup.id,
      'itemCount', jsonb_array_length(v_items)
    )
  );

  insert into public.notifications (user_id, title, message)
  values (
    v_backup.id,
    'Handover acknowledgment requested',
    format(
      '%s assigned you as backup for leave from %s to %s. Review and accept or decline the handover.',
      v_profile.name,
      v_request.start_date,
      v_request.end_date
    )
  );

  return jsonb_build_object(
    'planId', v_plan.id,
    'leaveRequestId', v_request.id,
    'backupUserId', v_backup.id,
    'backupName', v_backup.name,
    'summary', v_plan.summary,
    'items', v_items,
    'status', v_plan.status
  );
end;
$$;

create or replace function public.submit_leave_request_v2(
  p_leave_type text,
  p_start_date date,
  p_end_date date,
  p_reason text,
  p_coverage_snapshot_id uuid default null,
  p_handover jsonb default null
)
returns setof public.leave_requests
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_profile public.profiles;
  v_snapshot public.leave_coverage_snapshots;
  v_evaluation public.leave_policy_evaluations;
  v_request public.leave_requests;
  v_snapshot_id uuid;
  v_preview jsonb;
  v_remaining integer;
  v_overlap boolean;
begin
  v_profile := private.require_approved_profile();

  if p_leave_type not in ('annual', 'sick', 'casual', 'parental') then
    raise exception 'Invalid leave type';
  end if;
  if p_start_date is null or p_end_date is null or p_end_date < p_start_date then
    raise exception 'End date must be on or after start date';
  end if;
  if char_length(btrim(coalesce(p_reason, ''))) = 0 then
    raise exception 'A reason is required';
  end if;

  v_snapshot_id := p_coverage_snapshot_id;
  if v_snapshot_id is null then
    v_preview := public.preview_leave_request(
      p_leave_type,
      p_start_date,
      p_end_date,
      p_reason
    );
    v_snapshot_id := (v_preview ->> 'coverageSnapshotId')::uuid;
  end if;

  select snapshot.*
  into v_snapshot
  from public.leave_coverage_snapshots snapshot
  where snapshot.id = v_snapshot_id
    and snapshot.user_id = v_profile.id
  for update;

  if not found then
    raise exception 'Coverage preview not found' using errcode = 'P0002';
  end if;
  if v_snapshot.used_at is not null then
    raise exception 'This coverage preview has already been used';
  end if;
  if v_snapshot.expires_at < now() then
    raise exception 'This coverage preview has expired. Preview the dates again.';
  end if;
  if v_snapshot.leave_type <> p_leave_type
     or v_snapshot.start_date <> p_start_date
     or v_snapshot.end_date <> p_end_date
     or lower(btrim(v_snapshot.department)) <> lower(btrim(v_profile.department))
     or lower(btrim(v_snapshot.employee_title)) <> lower(btrim(v_profile.title)) then
    raise exception 'The submitted request does not match its coverage preview';
  end if;

  select evaluation.*
  into v_evaluation
  from public.leave_policy_evaluations evaluation
  where evaluation.id = v_snapshot.policy_evaluation_id
    and evaluation.user_id = v_profile.id;

  if not found then
    raise exception 'Policy evaluation not found' using errcode = 'P0002';
  end if;
  if v_evaluation.overall_status = 'fail' then
    raise exception 'This request does not satisfy the leave policy';
  end if;

  select case p_leave_type
    when 'annual' then balance.annual_total - balance.annual_used
    when 'sick' then balance.sick_total - balance.sick_used
    when 'casual' then balance.casual_total - balance.casual_used
    when 'parental' then balance.parental_total - balance.parental_used
  end
  into v_remaining
  from public.leave_balances balance
  where balance.user_id = v_profile.id
  for update;

  if v_snapshot.business_days > greatest(coalesce(v_remaining, 0), 0) then
    raise exception 'The current leave balance is no longer sufficient';
  end if;

  select exists (
    select 1
    from public.leave_requests request
    where request.user_id = v_profile.id
      and request.status in ('pending', 'approved', 'cancellation_pending')
      and daterange(request.start_date, request.end_date, '[]')
          && daterange(p_start_date, p_end_date, '[]')
  ) into v_overlap;

  if v_overlap then
    raise exception 'The selected dates overlap an active leave request';
  end if;

  if v_snapshot.handover_required and p_handover is null then
    raise exception 'A handover plan is required for this request';
  end if;

  insert into public.leave_requests (
    user_id,
    employee_name,
    employee_email,
    department,
    leave_type,
    start_date,
    end_date,
    total_days,
    reason,
    policy_evaluation_id,
    coverage_snapshot_id,
    coverage_risk_level,
    handover_required,
    handover_requirement_reasons
  ) values (
    v_profile.id,
    v_profile.name,
    v_profile.email,
    v_profile.department,
    p_leave_type,
    p_start_date,
    p_end_date,
    v_snapshot.business_days,
    btrim(p_reason),
    v_evaluation.id,
    v_snapshot.id,
    v_snapshot.risk_level,
    v_snapshot.handover_required,
    v_snapshot.handover_reasons
  ) returning * into v_request;

  update public.leave_coverage_snapshots
  set used_at = now()
  where id = v_snapshot.id;

  insert into public.audit_logs (
    leave_id,
    employee_id,
    actor_id,
    actor_name,
    actor_role,
    action,
    previous_status,
    new_status,
    reason
  ) values (
    v_request.id,
    v_profile.id,
    v_profile.id,
    v_profile.name,
    'employee',
    'leave_submitted',
    'none',
    'pending',
    p_reason
  );

  if p_handover is not null then
    perform public.save_handover_plan(v_request.id, p_handover);
  end if;

  return next v_request;
end;
$$;

create or replace function public.respond_to_handover(
  p_plan_id uuid,
  p_response text,
  p_comment text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_profile public.profiles;
  v_plan public.leave_handover_plans;
  v_status text;
begin
  v_profile := private.require_approved_profile();
  v_status := case lower(btrim(coalesce(p_response, '')))
    when 'accept' then 'accepted'
    when 'accepted' then 'accepted'
    when 'decline' then 'declined'
    when 'declined' then 'declined'
    when 'reject' then 'declined'
    when 'rejected' then 'declined'
    else null
  end;

  if v_status is null then
    raise exception 'Response must be accept or decline';
  end if;
  if char_length(coalesce(p_comment, '')) > 2000 then
    raise exception 'Response comment cannot exceed 2000 characters';
  end if;

  select plan.*
  into v_plan
  from public.leave_handover_plans plan
  where plan.id = p_plan_id
    and plan.backup_user_id = v_profile.id
  for update;

  if not found then
    raise exception 'Assigned handover not found' using errcode = 'P0002';
  end if;
  if v_plan.status <> 'pending' then
    raise exception 'This handover has already been answered';
  end if;

  update public.leave_handover_plans
  set status = v_status,
      response_comment = nullif(btrim(coalesce(p_comment, '')), ''),
      responded_at = now(),
      updated_at = now()
  where id = v_plan.id
  returning * into v_plan;

  insert into public.leave_handover_events (
    plan_id,
    actor_id,
    event_type,
    comment
  ) values (
    v_plan.id,
    v_profile.id,
    v_status,
    btrim(coalesce(p_comment, ''))
  );

  insert into public.notifications (user_id, title, message)
  values (
    v_plan.employee_id,
    case when v_status = 'accepted'
      then 'Handover accepted'
      else 'Handover declined' end,
    format(
      '%s %s your handover request.%s',
      v_profile.name,
      v_status,
      case when char_length(btrim(coalesce(p_comment, ''))) = 0
        then '' else ' Comment: ' || btrim(p_comment) end
    )
  );

  return jsonb_build_object(
    'planId', v_plan.id,
    'leaveRequestId', v_plan.leave_request_id,
    'status', v_plan.status,
    'responseComment', v_plan.response_comment,
    'respondedAt', v_plan.responded_at
  );
end;
$$;

create or replace function private.enforce_intelligent_approval()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
  if new.status = 'approved' and old.status is distinct from 'approved' then
    if exists (
      select 1
      from public.leave_policy_evaluations evaluation
      where evaluation.id = new.policy_evaluation_id
        and evaluation.overall_status = 'warning'
    ) and char_length(btrim(coalesce(new.manager_comment, ''))) = 0 then
      raise exception 'A manager comment is required for a policy warning';
    end if;

    if new.coverage_risk_level = 'high'
       and char_length(btrim(coalesce(new.approval_override_reason, ''))) < 20 then
      raise exception 'High-risk approval requires an override reason of at least 20 characters';
    end if;

    if new.handover_required and not exists (
      select 1
      from public.leave_handover_plans plan
      where plan.leave_request_id = new.id
        and plan.status = 'accepted'
    ) then
      raise exception 'The assigned backup must accept the required handover before approval';
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists enforce_intelligent_approval on public.leave_requests;
create trigger enforce_intelligent_approval
before update of status on public.leave_requests
for each row execute function private.enforce_intelligent_approval();

create or replace function public.process_leave_request_v2(
  p_request_id uuid,
  p_action text,
  p_comment text default '',
  p_override_reason text default ''
)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_manager public.profiles;
  v_request public.leave_requests;
  v_next_status public.leave_status;
  v_remaining integer;
begin
  v_manager := private.require_approved_profile();
  if v_manager.role <> 'manager' or not public.is_manager(v_manager.id) then
    raise exception 'Manager access required' using errcode = '42501';
  end if;
  if p_action not in ('approve', 'reject') then
    raise exception 'Unsupported action';
  end if;
  if char_length(coalesce(p_comment, '')) > 2000 then
    raise exception 'Manager comment cannot exceed 2000 characters';
  end if;

  select request.*
  into v_request
  from public.leave_requests request
  where request.id = p_request_id
  for update;

  if not found then
    raise exception 'Leave request not found' using errcode = 'P0002';
  end if;
  if v_request.status <> 'pending' then
    raise exception 'Only pending requests can be processed';
  end if;

  if exists (
    select 1
    from public.leave_policy_evaluations evaluation
    where evaluation.id = v_request.policy_evaluation_id
      and evaluation.overall_status = 'warning'
  ) and char_length(btrim(coalesce(p_comment, ''))) = 0 then
    raise exception 'A manager comment is required for a policy warning';
  end if;

  if p_action = 'approve' then
    if v_request.coverage_risk_level = 'high'
       and char_length(btrim(coalesce(p_override_reason, ''))) < 20 then
      raise exception 'High-risk approval requires an override reason of at least 20 characters';
    end if;

    if v_request.handover_required and not exists (
      select 1
      from public.leave_handover_plans plan
      where plan.leave_request_id = v_request.id
        and plan.status = 'accepted'
    ) then
      raise exception 'The assigned backup must accept the required handover before approval';
    end if;

    select case v_request.leave_type
      when 'annual' then balance.annual_total - balance.annual_used
      when 'sick' then balance.sick_total - balance.sick_used
      when 'casual' then balance.casual_total - balance.casual_used
      when 'parental' then balance.parental_total - balance.parental_used
    end
    into v_remaining
    from public.leave_balances balance
    where balance.user_id = v_request.user_id
    for update;

    if v_request.total_days > greatest(coalesce(v_remaining, 0), 0) then
      raise exception 'The employee no longer has sufficient leave balance';
    end if;

    update public.leave_balances balance
    set annual_used = balance.annual_used
        + case when v_request.leave_type = 'annual' then v_request.total_days else 0 end,
        sick_used = balance.sick_used
        + case when v_request.leave_type = 'sick' then v_request.total_days else 0 end,
        casual_used = balance.casual_used
        + case when v_request.leave_type = 'casual' then v_request.total_days else 0 end,
        parental_used = balance.parental_used
        + case when v_request.leave_type = 'parental' then v_request.total_days else 0 end,
        updated_at = now()
    where balance.user_id = v_request.user_id;
  end if;

  v_next_status := case when p_action = 'approve'
    then 'approved'::public.leave_status
    else 'rejected'::public.leave_status end;

  update public.leave_requests
  set status = v_next_status,
      manager_comment = p_comment,
      approval_override_reason = case
        when p_action = 'approve' and coverage_risk_level = 'high'
          then btrim(p_override_reason)
        else approval_override_reason end,
      processed_at = now(),
      processed_by = v_manager.id,
      updated_at = now(),
      approved_at = case when p_action = 'approve' then now() else approved_at end,
      rejected_at = case when p_action = 'reject' then now() else rejected_at end
  where id = v_request.id;

  insert into public.notifications (user_id, title, message)
  values (
    v_request.user_id,
    case when p_action = 'approve' then 'Leave approved' else 'Leave request declined' end,
    format(
      'Your %s leave from %s to %s was %s.%s',
      v_request.leave_type,
      v_request.start_date,
      v_request.end_date,
      case when p_action = 'approve' then 'approved' else 'declined' end,
      case when char_length(btrim(coalesce(p_comment, ''))) = 0
        then '' else ' Comment: ' || btrim(p_comment) end
    )
  );

  insert into public.audit_logs (
    leave_id,
    employee_id,
    actor_id,
    actor_name,
    actor_role,
    action,
    previous_status,
    new_status,
    reason
  ) values (
    v_request.id,
    v_request.user_id,
    v_manager.id,
    v_manager.name,
    'hr',
    case when p_action = 'approve' then 'leave_approved' else 'leave_rejected' end,
    'pending',
    v_next_status::text,
    case
      when p_action = 'approve' and v_request.coverage_risk_level = 'high'
        then btrim(p_override_reason)
      else p_comment end
  );
end;
$$;

alter table public.leave_policy_versions enable row level security;
alter table public.leave_policy_evaluations enable row level security;
alter table public.department_coverage_rules enable row level security;
alter table public.critical_role_rules enable row level security;
alter table public.leave_coverage_snapshots enable row level security;
alter table public.leave_coverage_snapshot_days enable row level security;
alter table public.leave_coverage_alternatives enable row level security;
alter table public.leave_handover_plans enable row level security;
alter table public.leave_handover_items enable row level security;
alter table public.leave_handover_events enable row level security;

create policy leave_policy_versions_select
on public.leave_policy_versions
for select to authenticated
using (true);

create policy leave_policy_versions_insert
on public.leave_policy_versions
for insert to authenticated
with check (public.is_manager());

create policy leave_policy_evaluations_select
on public.leave_policy_evaluations
for select to authenticated
using (user_id = (select auth.uid()) or public.is_manager());

create policy department_coverage_rules_select
on public.department_coverage_rules
for select to authenticated
using (true);

create policy department_coverage_rules_insert
on public.department_coverage_rules
for insert to authenticated
with check (public.is_manager());

create policy department_coverage_rules_update
on public.department_coverage_rules
for update to authenticated
using (public.is_manager())
with check (public.is_manager());

create policy department_coverage_rules_delete
on public.department_coverage_rules
for delete to authenticated
using (public.is_manager());

create policy critical_role_rules_select
on public.critical_role_rules
for select to authenticated
using (true);

create policy critical_role_rules_insert
on public.critical_role_rules
for insert to authenticated
with check (public.is_manager());

create policy critical_role_rules_update
on public.critical_role_rules
for update to authenticated
using (public.is_manager())
with check (public.is_manager());

create policy critical_role_rules_delete
on public.critical_role_rules
for delete to authenticated
using (public.is_manager());

create policy leave_coverage_snapshots_select
on public.leave_coverage_snapshots
for select to authenticated
using (user_id = (select auth.uid()) or public.is_manager());

create policy leave_coverage_snapshot_days_select
on public.leave_coverage_snapshot_days
for select to authenticated
using (exists (
  select 1
  from public.leave_coverage_snapshots snapshot
  where snapshot.id = leave_coverage_snapshot_days.snapshot_id
    and (snapshot.user_id = (select auth.uid()) or public.is_manager())
));

create policy leave_coverage_alternatives_select
on public.leave_coverage_alternatives
for select to authenticated
using (exists (
  select 1
  from public.leave_coverage_snapshots snapshot
  where snapshot.id = leave_coverage_alternatives.snapshot_id
    and (snapshot.user_id = (select auth.uid()) or public.is_manager())
));

create policy leave_handover_plans_select
on public.leave_handover_plans
for select to authenticated
using (
  employee_id = (select auth.uid())
  or backup_user_id = (select auth.uid())
  or public.is_manager()
);

create policy leave_handover_items_select
on public.leave_handover_items
for select to authenticated
using (exists (
  select 1
  from public.leave_handover_plans plan
  where plan.id = leave_handover_items.plan_id
    and (
      plan.employee_id = (select auth.uid())
      or plan.backup_user_id = (select auth.uid())
      or public.is_manager()
    )
));

create policy leave_handover_events_select
on public.leave_handover_events
for select to authenticated
using (exists (
  select 1
  from public.leave_handover_plans plan
  where plan.id = leave_handover_events.plan_id
    and (
      plan.employee_id = (select auth.uid())
      or plan.backup_user_id = (select auth.uid())
      or public.is_manager()
    )
));

revoke all on public.leave_policy_versions from public, anon, authenticated;
revoke all on public.leave_policy_evaluations from public, anon, authenticated;
revoke all on public.department_coverage_rules from public, anon, authenticated;
revoke all on public.critical_role_rules from public, anon, authenticated;
revoke all on public.leave_coverage_snapshots from public, anon, authenticated;
revoke all on public.leave_coverage_snapshot_days from public, anon, authenticated;
revoke all on public.leave_coverage_alternatives from public, anon, authenticated;
revoke all on public.leave_handover_plans from public, anon, authenticated;
revoke all on public.leave_handover_items from public, anon, authenticated;
revoke all on public.leave_handover_events from public, anon, authenticated;
revoke all on sequence public.leave_policy_versions_version_number_seq from public, anon, authenticated;

grant select, insert on public.leave_policy_versions to authenticated;
grant usage, select on sequence public.leave_policy_versions_version_number_seq to authenticated;
grant select on public.leave_policy_evaluations to authenticated;
grant select, insert, update, delete on public.department_coverage_rules to authenticated;
grant select, insert, update, delete on public.critical_role_rules to authenticated;
grant select on public.leave_coverage_snapshots to authenticated;
grant select on public.leave_coverage_snapshot_days to authenticated;
grant select on public.leave_coverage_alternatives to authenticated;
grant select on public.leave_handover_plans to authenticated;
grant select on public.leave_handover_items to authenticated;
grant select on public.leave_handover_events to authenticated;

revoke all on function private.is_business_day(date) from public, anon, authenticated;
revoke all on function private.business_days_between(date, date) from public, anon, authenticated;
revoke all on function private.business_date_after(date, integer) from public, anon, authenticated;
revoke all on function private.apply_authoritative_business_days() from public, anon, authenticated;
revoke all on function private.require_approved_profile() from public, anon, authenticated;
revoke all on function private.create_policy_evaluation(uuid, text, date, date, text) from public, anon, authenticated;
revoke all on function private.calculate_coverage(uuid, text, text, date, date) from public, anon, authenticated;
revoke all on function private.enforce_intelligent_approval() from public, anon, authenticated;

revoke all on function public.preview_leave_request(text, date, date, text) from public, anon;
revoke all on function public.get_handover_candidates() from public, anon;
revoke all on function public.get_assigned_handovers() from public, anon;
revoke all on function public.save_handover_plan(uuid, jsonb) from public, anon;
revoke all on function public.submit_leave_request_v2(text, date, date, text, uuid, jsonb) from public, anon;
revoke all on function public.respond_to_handover(uuid, text, text) from public, anon;
revoke all on function public.process_leave_request_v2(uuid, text, text, text) from public, anon;

grant execute on function public.preview_leave_request(text, date, date, text) to authenticated;
grant execute on function public.get_handover_candidates() to authenticated;
grant execute on function public.get_assigned_handovers() to authenticated;
grant execute on function public.save_handover_plan(uuid, jsonb) to authenticated;
grant execute on function public.submit_leave_request_v2(text, date, date, text, uuid, jsonb) to authenticated;
grant execute on function public.respond_to_handover(uuid, text, text) to authenticated;
grant execute on function public.process_leave_request_v2(uuid, text, text, text) to authenticated;

comment on table public.leave_policy_versions is
  'Append-only, effective-dated leave policy definitions used for explainable evaluations.';
comment on table public.leave_policy_evaluations is
  'Immutable per-preview policy results with human-readable pass, warning and fail checks.';
comment on table public.department_coverage_rules is
  'Effective-dated staffing thresholds used to score department coverage.';
comment on table public.critical_role_rules is
  'Effective-dated minimum staffing requirements for exact job titles in a department.';
comment on table public.leave_coverage_snapshots is
  'Immutable aggregate coverage preview owned by one employee; contains no coworker identities.';
comment on table public.leave_coverage_snapshot_days is
  'Aggregate per-business-day facts for a coverage snapshot; contains counts only.';
comment on table public.leave_coverage_alternatives is
  'The three lowest-risk future date ranges calculated for a coverage snapshot.';
comment on table public.leave_handover_plans is
  'Employee handover plan assigned to one approved backup coworker.';
comment on table public.leave_handover_items is
  'Ordered responsibilities and resources included in a handover plan.';
comment on table public.leave_handover_events is
  'Append-only audit events for handover creation and backup responses.';

comment on column public.leave_requests.policy_evaluation_id is
  'Explainable policy evaluation accepted when this request was submitted.';
comment on column public.leave_requests.coverage_snapshot_id is
  'Immutable aggregate staffing snapshot accepted when this request was submitted.';
comment on column public.leave_requests.coverage_risk_level is
  'Low, medium or high risk copied from the accepted coverage snapshot.';
comment on column public.leave_requests.handover_required is
  'True for requests of at least three business days, critical roles or high coverage risk.';
comment on column public.leave_requests.approval_override_reason is
  'Manager justification of at least 20 characters when approving a high-risk request.';

comment on function public.preview_leave_request(text, date, date, text) is
  'Evaluates policy and aggregate team coverage, persists an expiring snapshot and returns three alternatives.';
comment on function private.apply_authoritative_business_days() is
  'Forces every legacy and v2 leave write to use the holiday-aware business-day calculation.';
comment on function public.get_handover_candidates() is
  'Returns the minimum safe coworker directory needed to select an approved backup in the caller department.';
comment on function public.get_assigned_handovers() is
  'Returns only handovers assigned to the authenticated caller as backup.';
comment on function public.save_handover_plan(uuid, jsonb) is
  'Creates or replaces a pending handover using {backupUserId,summary,items:[{title,details?,dueDate?,resourceUrl?}]}.';
comment on function public.submit_leave_request_v2(text, date, date, text, uuid, jsonb) is
  'Atomically submits a validated leave request and, when supplied, its required handover plan.';
comment on function public.respond_to_handover(uuid, text, text) is
  'Allows only the assigned backup to accept or decline a pending handover.';
comment on function public.process_leave_request_v2(uuid, text, text, text) is
  'Processes a pending request while enforcing accepted handovers, current balances and high-risk justification.';

commit;
